const blogs = [
    {
        id: '1',
        title: 'Have evolved over the years sometimes accident.',
        screens: 'images/blog/img-1.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2020',
        blogSingleImg:'images/blog-details/img-1.jpg', 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '2',
        title: ' The Internet tend to repeat predefined chunks.',
        screens: 'images/blog/img-2.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        blogSingleImg:'images/blog-details/img-2.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
    {
        id: '3',
        title: 'The standard chunk of used since the interested.',
        screens: 'images/blog/img-3.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Aliza Anny',
        authorTitle:'Art Director',
        create_at: '22 Dec,2022',
        blogSingleImg:'images/blog-details/img-3.jpg',
        comment:'95',
        blClass:'format-video',
    },
    {
        id: '4',
        title: ' The Internet tend to repeat predefined chunks.',
        screens: 'images/blog/img-2.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        blogSingleImg:'images/blog-details/img-2.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
];
export default blogs;