
const Services = [
    {
        Id: '1',
        sImgS:'images/service-single/graphics/img-1.jpg',
        sTitle: 'Graphic Design',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-vector',
        ssImg1:'images/service-single/graphics/img-2.jpg',
        ssImg2:'images/service-single/graphics/img-3.jpg',
    },
    {
        Id: '2',
        sImgS:'images/service-single/brand/img-1.jpg',
        sTitle: 'Brand Identity',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-palette',
        ssImg1:'images/service-single/brand/img-2.jpg',
        ssImg2:'images/service-single/brand/img-3.jpg',
    },
    {
        Id: '3',
        sImgS:'images/service-single/ux/img-1.jpg',
        sTitle: 'UI/UX Design',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-add',
        ssImg1:'images/service-single/ux/img-3.jpg',
        ssImg2:'images/service-single/ux/img-3.jpg',
    },
    {
        Id: '4',
        sImgS:'images/service-single/development/img-1.jpg',
        sTitle: 'Web Development',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-coding',
        ssImg1:'images/service-single/development/img-2.jpg',
        ssImg2:'images/service-single/development/img-3.jpg',
    },
    {
        Id: '5',
        sImgS:'images/service-single/app/img-1.jpg',
        sTitle: 'App Development',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-app-development',
        ssImg1:'images/service-single/app/img-2.jpg',
        ssImg2:'images/service-single/app/img-3.jpg',
    },
    {
        Id: '6',
        sImgS:'images/service-single/softwere/img-1.jpg',
        sTitle: 'Softwere Development',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-smartphone',
        ssImg1:'images/service-single/softwere/img-2.jpg',
        ssImg2:'images/service-single/softwere/img-3.jpg',
    },
    {
        Id: '7',
        sImgS:'images/service-single/sm/img-1.jpg',
        sTitle: 'Social Media Marketing',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-social-media',
        ssImg1:'images/service-single/sm/img-2.jpg',
        ssImg2:'images/service-single/sm/img-3.jpg',
    },
    {
        Id: '8',
        sImgS:'images/service-single/dm/img-1.jpg',
        sTitle: 'Digital Marketing',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-promotion',
        ssImg1:'images/service-single/dm/img-2.jpg',
        ssImg2:'images/service-single/dm/img-3.jpg',
    },
    {
        Id: '9',
        sImgS:'images/service-single/email/img-1.jpg',
        sTitle: 'Email Marketing',
        description:'Explain to you how all this mistaken idea of denouncing pleasure born and give you complete account the system.',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-email-marketing',
        ssImg1:'images/service-single/email/img-2.jpg',
        ssImg2:'images/service-single/email/img-3.jpg',
    },
]    

export default Services;